# Generated by Django 2.1.2 on 2018-10-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursverwaltung', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kunde',
            name='id',
        ),
        migrations.AddField(
            model_name='kunde',
            name='kd_nr',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
